# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fireCloud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Storage'

  # Pods for fireCloud

  target 'fireCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fireCloudUITests' do
    # Pods for testing
  end

end
